// City definitions — add a city by appending an entry here (that's the whole job).
// Coordinates are [longitude, latitude]; camera is the flyTo view per landmark,
// with bearing tuned for the best angle.
export const CITIES = {
  seoul: {
    label: 'SEOUL',
    name: 'Seoul',
    tagline: 'Interactive 3D Map of Seoul',
    view: { center: [126.978, 37.5665], zoom: 15.2, pitch: 60, bearing: -17 },
    landmarks: [
      {
        id: 'lotte-tower',
        name: 'Lotte World Tower',
        coords: [127.1025, 37.5126],
        camera: { zoom: 15.6, pitch: 65, bearing: -40 },
        chips: ['555 m', '123 floors', 'Completed 2017'],
        desc: 'The tallest building in South Korea and one of the tallest skyscrapers in the world. The centerpiece of the Jamsil skyline.',
      },
      {
        id: 'namsan-tower',
        name: 'N Seoul Tower',
        coords: [126.9883, 37.5512],
        camera: { zoom: 14.8, pitch: 68, bearing: 25 },
        chips: ['236 m tower', 'Mt. Namsan 262 m', 'Opened 1980'],
        desc: 'The iconic tower atop Mt. Namsan. Tower and mountain combined offer a panoramic view of Seoul from roughly 480 m above sea level.',
      },
      {
        id: 'sixty-three',
        name: '63 Building',
        coords: [126.9401, 37.5198],
        camera: { zoom: 15.4, pitch: 62, bearing: -25 },
        chips: ['249.6 m', '63 floors', 'Completed 1985'],
        desc: 'The golden landmark of Yeouido on the Han River. It was the tallest building in Asia at the time of its completion.',
      },
      {
        id: 'gyeongbokgung',
        name: 'Gyeongbokgung Palace',
        coords: [126.977, 37.5788],
        camera: { zoom: 15.8, pitch: 55, bearing: 0 },
        chips: ['Main royal palace', 'Founded 1395'],
        desc: 'The principal palace of the Joseon dynasty, set against Mt. Bugaksan and facing Gwanghwamun Square and the downtown skyline.',
      },
      {
        id: 'ddp',
        name: 'Dongdaemun Design Plaza',
        coords: [127.0095, 37.5665],
        camera: { zoom: 16.2, pitch: 58, bearing: 60 },
        chips: ['Zaha Hadid', 'Opened 2014'],
        desc: 'A neofuturistic landmark with flowing curved facades — one of the largest free-form buildings in the world.',
      },
      {
        id: 'assembly',
        name: 'National Assembly Building',
        coords: [126.914, 37.5319],
        camera: { zoom: 15.6, pitch: 60, bearing: -10 },
        chips: ['Yeouido', 'Completed 1975'],
        desc: 'The seat of the South Korean legislature at the western tip of Yeouido, its domed roof set against the Han River.',
      },
      {
        id: 'city-hall',
        name: 'Seoul City Hall & Gwanghwamun',
        coords: [126.978, 37.5665],
        camera: { zoom: 15.4, pitch: 60, bearing: -17 },
        chips: ['Downtown core'],
        desc: 'The heart of downtown Seoul — Deoksugung Palace, City Hall, Cheonggyecheon Stream, and Gwanghwamun Square.',
      },
    ],
  },

  nyc: {
    label: 'NYC',
    name: 'New York',
    tagline: 'Interactive 3D Map of New York City',
    view: { center: [-74.0115, 40.7115], zoom: 15.0, pitch: 62, bearing: -15 },
    landmarks: [
      {
        id: 'one-wtc',
        name: 'One World Trade Center',
        coords: [-74.0134, 40.7127],
        camera: { zoom: 15.8, pitch: 65, bearing: -30 },
        chips: ['541 m', '104 floors', 'Completed 2014'],
        desc: 'The tallest building in the Western Hemisphere, rising from the World Trade Center site at the tip of Lower Manhattan.',
      },
      {
        id: 'empire-state',
        name: 'Empire State Building',
        coords: [-73.9857, 40.7484],
        camera: { zoom: 15.6, pitch: 63, bearing: -25 },
        chips: ['381 m', '102 floors', 'Completed 1931'],
        desc: "Midtown's Art Deco icon — the tallest building in the world for nearly four decades after its completion.",
      },
      {
        id: 'chrysler',
        name: 'Chrysler Building',
        coords: [-73.9755, 40.7516],
        camera: { zoom: 15.9, pitch: 62, bearing: 30 },
        chips: ['319 m', '77 floors', 'Completed 1930'],
        desc: 'An Art Deco masterpiece crowned in stainless steel, briefly the tallest building in the world before the Empire State Building.',
      },
      {
        id: 'hudson-yards',
        name: '30 Hudson Yards & The Edge',
        coords: [-74.0009, 40.7536],
        camera: { zoom: 15.5, pitch: 64, bearing: -45 },
        chips: ['387 m', 'Sky deck', 'Completed 2019'],
        desc: 'The centerpiece of the Hudson Yards mega-development, with the highest outdoor sky deck in the Western Hemisphere.',
      },
      {
        id: 'billionaires-row',
        name: "Billionaires' Row",
        coords: [-73.9776, 40.7647],
        camera: { zoom: 15.3, pitch: 65, bearing: 160 },
        chips: ['Supertall canyon', '432 Park · Steinway'],
        desc: 'A row of pencil-thin supertalls along 57th Street overlooking Central Park — some of the skinniest skyscrapers ever built.',
      },
      {
        id: 'times-square',
        name: 'Times Square',
        coords: [-73.9855, 40.758],
        camera: { zoom: 16.0, pitch: 58, bearing: -20 },
        chips: ['Crossroads of the World'],
        desc: 'The neon heart of Midtown, where Broadway cuts diagonally across Seventh Avenue.',
      },
      {
        id: 'brooklyn-bridge',
        name: 'Brooklyn Bridge',
        coords: [-73.9969, 40.7061],
        camera: { zoom: 15.2, pitch: 60, bearing: -35 },
        chips: ['Opened 1883', 'Neo-Gothic towers'],
        desc: 'The 19th-century suspension icon spanning the East River between Lower Manhattan and Brooklyn.',
      },
    ],
  },
};

export const DEFAULT_CITY = 'seoul';
